DROP DATABASE IF EXISTS RESTAURANTE;

CREATE DATABASE RESTAURANTE;

USE RESTAURANTE;

CREATE TABLE PESSOA 
(
	PESS_ID_PESSOA INT         NOT NULL AUTO_INCREMENT,
	PESS_NM_NOME   VARCHAR(45) NOT NULL,
	PESS_NU_CPF    VARCHAR(11) NOT NULL,
	PRIMARY KEY (PESS_ID_PESSOA)
);


CREATE TABLE CLIENTE 
(
	PESS_ID_PESSOA INT NOT NULL,
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES PESSOA(PESS_ID_PESSOA)
);

CREATE TABLE ENDERECO 
(
	ENDE_ID_ENDERECO INT NOT NULL AUTO_INCREMENT, 
	ENDE_TX_LOGRADOURO VARCHAR(45) NOT NULL,
	PESS_ID_PESSOA INT NOT NULL,
	PRIMARY KEY (ENDE_ID_ENDERECO),
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES CLIENTE(PESS_ID_PESSOA)
);

CREATE TABLE TELEFONE
(
	TELE_ID_TELEFONE INT NOT NULL AUTO_INCREMENT,
	TELE_NU_TELEFONE VARCHAR(11) NOT NULL,
	PESS_ID_PESSOA INT NOT NULL,
	PRIMARY KEY (TELE_ID_TELEFONE),
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES CLIENTE(PESS_ID_PESSOA)
);

CREATE TABLE CARGO
(
	CARG_ID_CARGO INT NOT NULL AUTO_INCREMENT,
	CARG_NM_NOME VARCHAR(45),
	PRIMARY KEY (CARG_ID_CARGO)
);

CREATE TABLE FUNCIONARIO 
(
	PESS_ID_PESSOA INT NOT NULL,
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES PESSOA(PESS_ID_PESSOA)
);

CREATE TABLE FUNCIONARIO_CARGO 
(
	FUCA_ID_FUNCIONARIO_CARGO INT NOT NULL AUTO_INCREMENT,
	FUCA_DT_DATA DATETIME NOT NULL,
    PESS_ID_PESSOA INT NOT NULL,
	CARG_ID_CARGO INT NOT NULL ,
	PRIMARY KEY (FUCA_ID_FUNCIONARIO_CARGO),
	FOREIGN KEY (CARG_ID_CARGO) REFERENCES CARGO(CARG_ID_CARGO),
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES FUNCIONARIO(PESS_ID_PESSOA)
);

CREATE TABLE FUNCIONALIDADE 
(
	FUNC_ID_FUNCIONALIDADE INT NOT NULL AUTO_INCREMENT,
	FUNC_DC_DESCRICAO VARCHAR(45) NOT NULL,
	PRIMARY KEY (FUNC_ID_FUNCIONALIDADE)
);

CREATE TABLE CARGO_FUNCIONALIDADE 
(
	FUNC_ID_FUNCIONALIDADE INT NOT NULL,
	CARG_ID_CARGO INT NOT NULL,
	PRIMARY KEY (FUNC_ID_FUNCIONALIDADE, CARG_ID_CARGO),
	FOREIGN KEY (FUNC_ID_FUNCIONALIDADE) REFERENCES FUNCIONALIDADE(FUNC_ID_FUNCIONALIDADE),
	FOREIGN KEY (CARG_ID_CARGO) REFERENCES CARGO(CARG_ID_CARGO)
);

CREATE TABLE MESA
(
	MESA_ID_MESA INT NOT NULL AUTO_INCREMENT,
	MESA_NU_NUMERO INT NOT NULL,
	MESA_NU_QUANTIDADE_CADEIRA INT NOT NULL,
	PRIMARY KEY (MESA_ID_MESA)
);

CREATE TABLE COMANDA
(
	COMA_ID_COMANDA INT NOT NULL AUTO_INCREMENT,
	PESS_ID_PESSOA INT ,
	PRIMARY KEY (COMA_ID_COMANDA),
	FOREIGN KEY (PESS_ID_PESSOA) REFERENCES CLIENTE(PESS_ID_PESSOA)
); 

CREATE TABLE MESA_COMANDA 
(
	MECO_ID_MESA_COMANDA INT NOT NULL AUTO_INCREMENT,
	MESA_ID_MESA INT NOT NULL,
	COMA_ID_COMANDA INT NOT NULL,
	PRIMARY KEY (MECO_ID_MESA_COMANDA),
	FOREIGN KEY (MESA_ID_MESA) REFERENCES MESA(MESA_ID_MESA),
	FOREIGN KEY (COMA_ID_COMANDA) REFERENCES COMANDA(COMA_ID_COMANDA)
);


CREATE TABLE ITEM 
(
	ITEM_ID_ITEM INT NOT NULL AUTO_INCREMENT,
	ITEM_NM_NOME VARCHAR(45) NOT NULL,
	ITEM_VL_VALOR DECIMAL(6,2) NOT NULL,
	PRIMARY KEY (ITEM_ID_ITEM)
);

CREATE TABLE PEDIDO 
(
	PEDI_ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
	COMA_ID_COMANDA INT NOT NULL,
	PEDI_DT_PEDIDO DATETIME NOT NULL,
	PRIMARY KEY (PEDI_ID_PEDIDO),
	FOREIGN KEY (COMA_ID_COMANDA) REFERENCES COMANDA (COMA_ID_COMANDA)
);

CREATE TABLE ITEM_PEDIDO 
(
	ITPE_ID_ITEM_PEDIDO INT NOT NULL AUTO_INCREMENT,
	PEDI_ID_PEDIDO INT NOT NULL,
	ITEM_ID_ITEM INT NOT NULL,
	PRIMARY KEY (ITPE_ID_ITEM_PEDIDO),
	FOREIGN KEY (PEDI_ID_PEDIDO) REFERENCES PEDIDO (PEDI_ID_PEDIDO),
	FOREIGN KEY (ITEM_ID_ITEM) REFERENCES ITEM (ITEM_ID_ITEM)
);

CREATE TABLE CAIXA 
(
	CAIX_ID_CAIXA INT NOT NULL AUTO_INCREMENT,
	CAIX_VL_TOTAL DECIMAL(6,2) NOT NULL,
	COMA_ID_COMANDA INT NOT NULL,
	CAIX_VL_DESCONTO INT,
	PRIMARY KEY (CAIX_ID_CAIXA),
	FOREIGN KEY (COMA_ID_COMANDA) REFERENCES COMANDA (COMA_ID_COMANDA)
);

CREATE TABLE TIPO_PAGAMENTO 
(
	TIPA_ID_TIPO_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
	TIPA_DC_DESCRICAO VARCHAR(45),
	PRIMARY KEY (TIPA_ID_TIPO_PAGAMENTO)
);

CREATE TABLE CAIXA_TIPO_PAGAMENTO 
(
	CAIX_ID_CAIXA INT NOT NULL,
	TIPA_ID_TIPO_PAGAMENTO INT NOT NULL,
	PRIMARY KEY (CAIX_ID_CAIXA, TIPA_ID_TIPO_PAGAMENTO),
	FOREIGN KEY (CAIX_ID_CAIXA) REFERENCES CAIXA (CAIX_ID_CAIXA),
	FOREIGN KEY (TIPA_ID_TIPO_PAGAMENTO) REFERENCES TIPO_PAGAMENTO (TIPA_ID_TIPO_PAGAMENTO) 
);

