USE RESTAURANTE;

DROP VIEW IF EXISTS VW_PEDIDOS_COMANDA;

CREATE VIEW VW_PEDIDOS_COMANDA AS
SELECT C.COMA_ID_COMANDA AS ID_COMANDA, COUNT(P.PEDI_ID_PEDIDO) AS PEDIDOS
FROM COMANDA AS C
INNER JOIN PEDIDO AS P
ON C.COMA_ID_COMANDA = P.COMA_ID_COMANDA
WHERE C.COMA_ID_COMANDA = P.COMA_ID_COMANDA
GROUP BY C.COMA_ID_COMANDA;