-- ACESSO AO DATABASE 'SISTEMA_ACADEMICO'.
USE RESTAURANTE;


DROP TRIGGER IF EXISTS TGR_DEPOIS_INSERIR_ITEM_PEDIDO;

DELIMITER @@
CREATE TRIGGER TGR_DEPOIS_INSERIR_ITEM_PEDIDO
AFTER INSERT ON ITEM_PEDIDO
FOR EACH ROW
BEGIN
	DECLARE VALOR_TOTAL DECIMAL(6,2);
    DECLARE VALOR_DESCONTADO DECIMAL(6,2);
    DECLARE DESCONTO_EXISTE BOOLEAN;
    DECLARE DESCONTO INT;
    DECLARE ID_COMANDA INT;
    DECLARE ID_PEDIDO INT;
    
    SELECT PEDI_ID_PEDIDO INTO ID_PEDIDO
    FROM PEDIDO
    WHERE NEW.PEDI_ID_PEDIDO = PEDI_ID_PEDIDO;
    
    SELECT C.COMA_ID_COMANDA INTO ID_COMANDA
    FROM COMANDA AS C
    INNER JOIN PEDIDO AS P
    ON C.COMA_ID_COMANDA = P.COMA_ID_COMANDA
    WHERE ID_PEDIDO = P.PEDI_ID_PEDIDO;
    
    SELECT EXISTS (SELECT CAIX_VL_DESCONTO FROM CAIXA WHERE COMA_ID_COMANDA = ID_COMANDA) INTO DESCONTO_EXISTE;
	
	SELECT SUM(I.ITEM_VL_VALOR) INTO VALOR_TOTAL
    FROM COMANDA AS C
    INNER JOIN PEDIDO AS P 
    ON C.COMA_ID_COMANDA = P.COMA_ID_COMANDA
    INNER JOIN ITEM_PEDIDO AS ITPD
    ON P.PEDI_ID_PEDIDO = ITPD.PEDI_ID_PEDIDO
    INNER JOIN ITEM AS I 
    ON ITPD.ITEM_ID_ITEM = I.ITEM_ID_ITEM
    WHERE ID_COMANDA = P.COMA_ID_COMANDA;
    
	IF DESCONTO_EXISTE THEN
    SELECT CAIX_VL_DESCONTO INTO DESCONTO FROM CAIXA WHERE COMA_ID_COMANDA = ID_COMANDA; 
    SET VALOR_DESCONTADO = VALOR_TOTAL - DESCONTO;
    UPDATE CAIXA 
    SET CAIX_VL_TOTAL = VALOR_TOTAL, CAIX_VL_VALOR_DESCONTADO = VALOR_DESCONTADO, CAIX_VL_DESCONTO = DESCONTO
    WHERE ID_COMANDA = COMA_ID_COMANDA;
    ELSE
    UPDATE CAIXA 
    SET CAIX_VL_TOTAL = VALOR_TOTAL, CAIX_VL_VALOR_DESCONTADO = VALOR_TOTAL
    WHERE ID_COMANDA = COMA_ID_COMANDA;
    END IF;
   
END @@
DELIMITER ;

-- TESTE:
-- INSERT INTO ALUNO_PROFESSOR_DISCIPLINA_TURMA (ALUN_ID_MATRICULA, TURM_ID_TURMA, DISC_ID_DISCIPLINA, PROF_NU_MATRICULA) VALUES ('20171STADS0001', 2, 6, 2297520);