USE RESTAURANTE;
DROP FUNCTION IF EXISTS FNC_CARGO_FUNCIONARIO;

DELIMITER //
CREATE FUNCTION FNC_CARGO_FUNCIONARIO (NOME VARCHAR(45)) RETURNS VARCHAR(45)
BEGIN
    DECLARE CARGO VARCHAR(45);
    DECLARE VALOR_MAX INT;
    
    SELECT MAX(FC.FUCA_ID_FUNCIONARIO_CARGO) INTO VALOR_MAX
    FROM CARGO AS C 
    INNER JOIN FUNCIONARIO_CARGO AS FC
    ON C.CARG_ID_CARGO = FC.CARG_ID_CARGO
    WHERE FNC_ID_DA_PESSOA(NOME) = FC.PESS_ID_PESSOA;
    
    SELECT C.CARG_NM_NOME INTO CARGO
    FROM CARGO AS C 
    INNER JOIN FUNCIONARIO_CARGO AS FC
    ON C.CARG_ID_CARGO = FC.CARG_ID_CARGO
    WHERE VALOR_MAX = FC.FUCA_ID_FUNCIONARIO_CARGO;
      
        
	
    
        
    RETURN CARGO;
END //
DELIMITER ;