
DROP TRIGGER IF EXISTS TGR_DEPOIS_INSERIR_COMANDA;

DELIMITER @@
CREATE TRIGGER TGR_DEPOIS_INSERIR_COMANDA
AFTER INSERT ON COMANDA
FOR EACH ROW
BEGIN
	DECLARE ID_COMANDA INT;
    
    SELECT COMA_ID_COMANDA INTO ID_COMANDA
    FROM COMANDA
    WHERE NEW.COMA_ID_COMANDA = COMA_ID_COMANDA;
    
    INSERT INTO CAIXA ( CAIX_VL_TOTAL, COMA_ID_COMANDA, CAIX_VL_DESCONTO, CAIX_VL_VALOR_DESCONTADO)
    VALUES ('0.0', ID_COMANDA, '0.0', '0.0');
    
END @@
DELIMITER ;