DROP TRIGGER IF EXISTS TGR_ANTES_INSERIR_PESSOA;

DELIMITER @@
CREATE TRIGGER TGR_ANTES_INSERIR_PESSOA
BEFORE INSERT ON PESSOA
FOR EACH ROW
BEGIN
	DECLARE MENSAGEM_ERRO VARCHAR(128);
    DECLARE CPF VARCHAR(11);
    
    SELECT PESS_NU_CPF INTO CPF 
    FROM PESSOA
    WHERE NEW.PESS_NU_CPF = PESS_NU_CPF;

	IF CPF IS NOT NULL THEN

	SET MENSAGEM_ERRO = CONCAT('Esta pessoa já está cadastrada');
	SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MENSAGEM_ERRO;

	END IF;
END @@
DELIMITER ; 