DROP TRIGGER IF EXISTS TRG_ANTES_INSERIR_TELEFONE;

DELIMITER @@
CREATE TRIGGER TRG_ANTES_INSERIR_TELEFONE
BEFORE INSERT ON TELEFONE
FOR EACH ROW
BEGIN
DECLARE MENSAGEM_ERRO VARCHAR(128);
    DECLARE QUANTIDADE_TELEFONE INT;
    DECLARE LIMITE_TELEFONES INT;
    SET LIMITE_TELEFONES = 3;
    SELECT COUNT(PESS_ID_PESSOA) INTO QUANTIDADE_TELEFONE FROM TELEFONE WHERE PESS_ID_PESSOA = NEW.PESS_ID_PESSOA;
    IF QUANTIDADE_TELEFONE > LIMITE_TELEFONES THEN
SET MENSAGEM_ERRO = CONCAT('O limite de telefones para esse cliente foi atingido');
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MENSAGEM_ERRO;
END IF;
END @@
DELIMITER ;