DROP PROCEDURE IF EXISTS PRC_DELETAR_TELEFONE;

DELIMITER @@
CREATE PROCEDURE PRC_DELETAR_TELEFONE(IN CODIGO_CLIENTE INT,TELEFONE INT)
BEGIN
	DELETE FROM TELEFONE WHERE PESS_ID_PESSOA = CODIGO_CLIENTE;
END @@
DELIMITER ;