USE RESTAURANTE;

DROP FUNCTION IF EXISTS FNC_VALOR_DESCONTO;

DELIMITER //
CREATE FUNCTION FNC_VALOR_DESCONTO(ID_COMANDA_IN INT) RETURNS DECIMAL(6,2)
BEGIN
    DECLARE DESCONTO INT;
    DECLARE VALOR DECIMAL(6,2);
    
	SELECT CAIX_VL_DESCONTO INTO DESCONTO
    FROM CAIXA
    WHERE ID_COMANDA_IN = COMA_ID_COMANDA;
    
    SELECT CAIX_VL_TOTAL INTO VALOR
    FROM CAIXA
    WHERE ID_COMANDA_IN = COMA_ID_COMANDA;
    
    RETURN VALOR - DESCONTO;
END //
DELIMITER ;