DROP PROCEDURE IF EXISTS PRC_INSERIR_TELEFONE;

select * from TELEFONE;
DELIMITER @@
CREATE PROCEDURE PRC_INSERIR_TELEFONE (IN TELEFONE INT, IN ID_PESSOA INT)
BEGIN
INSERT INTO TELEFONE (TELE_NU_TELEFONE,PESS_ID_PESSOA)VALUES(TELEFONE,ID_PESSOA);
	END @@
DELIMITER ;



