DROP TRIGGER IF EXISTS TRG_ANTES_INSERIR_ENDERECO;

DELIMITER @@
CREATE TRIGGER TRG_ANTES_INSERIR_ENDERECO
BEFORE INSERT ON ENDERECO
FOR EACH ROW
BEGIN
DECLARE MENSAGEM_ERRO VARCHAR(128);
    DECLARE QUANTIDADE_ENDERECOS INT;
    DECLARE LIMITE_ENDERECOS INT;
    SET LIMITE_ENDERECOS = 2;
    SELECT COUNT(PESS_ID_PESSOA) INTO QUANTIDADE_ENDERECOS FROM ENDERECO WHERE PESS_ID_PESSOA = NEW.PESS_ID_PESSOA;
    IF QUANTIDADE_ENDERECOS > LIMITE_ENDERECOS THEN
	SET MENSAGEM_ERRO = CONCAT('O limite de endereços para está pessoa já foi atingido ');
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MENSAGEM_ERRO;
END IF;
END @@
DELIMITER ;