DROP PROCEDURE IF EXISTS PRC_INSERIR_FUNCIONARIO_CARGO;

DELIMITER @@
CREATE PROCEDURE PRC_INSERIR_FUNCIONARIO_CARGO(IN NOME INT ,IN CARGO INT)
BEGIN
	INSERT INTO FUNCIONARIO_CARGO (FUCA_DT_DATA,PESS_ID_PESSOA,CARG_ID_CARGO)
    VALUES(NOW(),NOME,CARGO);
END @@
DELIMITER ;